# Generated by Django 4.2.7 on 2023-12-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], max_length=31, verbose_name='Статус'),
        ),
    ]
