# Generated by Django 4.2.7 on 2023-11-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.TextField(null=True, verbose_name='Сделать до'),
        ),
    ]
