# Generated by Django 4.2.7 on 2023-11-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_task_created_at_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.TextField(max_length=3000, verbose_name='Задача'),
        ),
    ]
