# Generated by Django 4.2.7 on 2023-12-18 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_alter_type_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasktype",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_type",
                to="todo.task",
                verbose_name="Задача",
            ),
        ),
    ]
