# Generated by Django 4.2.7 on 2023-12-24 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0004_project_alter_tasktype_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tasks",
                to="todo.project",
                verbose_name="Проект",
            ),
            preserve_default=False,
        ),
    ]
