# Generated by Django 4.2.7 on 2023-12-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=3000, null=True, verbose_name='Описание'),
        ),
    ]
