# Generated by Django 4.2.7 on 2024-01-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0005_task_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="start_project",
            field=models.DateField(
                blank=True, null=True, verbose_name="Начало проекта"
            ),
        ),
    ]
