# Generated by Django 4.2.7 on 2023-12-19 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0005_alter_task_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(4),
                    django.core.validators.MaxLengthValidator(50),
                ],
                verbose_name="Задача",
            ),
        ),
    ]
