# Generated by Django 4.2.7 on 2023-12-03 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=3000, unique=True, verbose_name='Задача')),
                ('descript', models.TextField(blank=True, max_length=400, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='todo.typetask', verbose_name='Тип'),
        ),
    ]
