# Generated by Django 4.2.7 on 2023-12-19 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0006_alter_task_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                max_length=3000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(20)],
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[django.core.validators.MinLengthValidator(4)],
                verbose_name="Задача",
            ),
        ),
    ]
