# Generated by Django 4.2.7 on 2023-12-19 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0007_alter_task_description_alter_task_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                max_length=3000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(300)],
                verbose_name="Описание",
            ),
        ),
    ]
