# Generated by Django 4.2.7 on 2024-01-09 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todo", "0008_task_users_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="users",
        ),
        migrations.AddField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(
                null=True,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
